### ISSUE TITLE
Broadcast an Event on every step

### ISSUE THREAD

**Issue by marchrius** [cloudyrock/mongock#200]
At the moment we don't know when a migration starts/finishes and the access to the database is not locked by mongock, so an insertion at application startup can produce errors for not yet initialised collections (e.g. multi-document transaction exception)

Is there an event publisher or is planned to be?

Eg.

```
| MongockStartingEvent
|_ MongockStartedEvent
|   |_ MongockChahgeLogStartingEvent
|   |_ MongockChahgeLogStartedEvent
|   |  |_ MongockChahgeSetStartingEvent
|   |  |_ MongockChahgeSetFinishedEvent
|   |_ MongockChahgeLogFinishedEven
|_ MongockFinishedEvent
```

**Comment by dieppa** [comment]
Hello @marchrius ,

I am glad you ask that because we have planned to add this feature. When I say "plan" I mean we have decided to add it, however there are some other priorities first and I cannot tell you when exactly this will be available, but after transactions, recovery, undo and some other, this is next, so my expectation is beginning of august.

Thanks
