### ISSUE TITLE
How to rollback already applied changeset?

### ISSUE THREAD

**Issue by jfenuk** [cloudyrock/mongock#219]
Hi guys,

Could you please advise what is the preferable way to rollback applied changes by some Changeset?
Flyway/Liquibase provide out of the box undo migration mechanism, but what about MongoDB world and Mongock?

**Comment by dieppa** [comment]
Hi @jfenuk , glad you ask that.

Although Mongock doesn't provide anything just now, we are working on several mechanism:
- **Transactions**: For MongoDB 4.0 and higher. We'll start providing all-or-nothing for the entire migration. But the plan is to provide two more levels: per changeSet and changeLog. The last one is the recommended. 
**We are finishing this feature, in test phase and will be released soon**

- **Recovery**: For non-transactional environments, the recovery mechanism will allow you to execute some actions when a changeSet fails to simulate your manual "rollback". It works retrospectively in reverse order, so when a changeSet fails, it will run all the recovery methods associated with the executed changeSets, starting from the most recently executed.
**We haven't started te development. We'll start once transactions are released in an stable version"

- **Undo**: This is not really a rollback mechanism, but it's belong to the "recovery" area. This feature will allow you to "undo" any changeSet you "regret". Let's say in a previous migration you executed a changeSet that now realise should never be added. In this cases is where UNDO operations come handy. You tell Mongock to execute that operation to "repair" the actions of the undesired changeSet. You may wonder , why not add a standard changeSet that do the "undo" job. While this would work, it will force Mongock to always run the undesired changeSet. So it could happen that you provide an UNDO operation for a changeSet you don't want to be executed, but it will, to then later, "fixed". When providing and UNDO operation associated to a changeSet, Mongock will check if the changeSet has been already executed. If that is the case, it will run the UNDO operation, otherwise neither the changeSet nor the UNDO will be ever executed.
**We haven't started te development. We'll start once transactions are released in an stable version"



If there is anything you think we could add or improve in this area, or anything we have missed, you're suggestions are welcome ;)
