### ISSUE TITLE
How to use @ChangeSe'ts correctly?

### ISSUE THREAD

**Issue by jfenuk** [cloudyrock/mongock#237]
@dieppa Could you please advice how should I use Mongock correctly for solving the following task:

For each Document in the existing Collection:
- rename existing attribute;
- update value of the existing attribute;
- and a new attribute.

I am going to create only one @ChangeLog class to achieve the goal, but do I need to create a separate @ChangeSet method per each task? I mean, do I need to create in the scope of single @ChangeLog 3 separate @changeSet's, like: 
    @ChangeSet(order = "001", author = "developer", id = "rename_existing_attribute")
    @ChangeSet(order = "002", author = "developer", id = "update_value")
    @ChangeSet(order = "003", author = "developer", id = "add_new_attribute")

all it will be totally fine to make all changes in the scope of one @ChangeSet?

**Comment by dieppa** [comment]
Hello @jfenuk,some questions firsts?
1) transactions available?
2) Collection size aprox. Are we speaking about dozens, hundres, thousands, millions, etc.?
3) Which environment are you using(production)? Some containerised environment like Kubernetes, for example?
4) High Availability is a critical factor un your system?

With that, I think I can suggest you the best approach from my point of view ;)

**Comment by jfenuk** [comment]
Hi @dieppa thank you for your quick response!

1. No;
2. Hundreds of documents;
3. Servers somewhere is the AWS ecosystem;
4. No.

**Comment by dieppa** [comment]
OK, so it's an easy one.

First, I recommend organising your changeLogs per migration. People tend to do it per component/domain, etc. But as you will likely have several domains involved in the same migration and they would probably be codependent with each other, it doesn't make much sense to try to make them independent, because in fact, they are not. For example, if you want to make an update your application to make "dog"(a domain) "walkable". You probably need to add the attribute "collar" to dogs and update the domain "street" to make them "dog friendly" by adding whatever field needed. I suggest to update both domains in the same changeLog(probably different changeSets) and describe the changeLog with the migration's purpose(dog walkable, for example)

Once made that clear, I would split your work in the following tasks(each of them a separate changeSet in the same ChangeLog)
1) Add new attribute with the value. Instead of renaming it, I would add a new attribute with the new name and the value you want.
2) Remove the old attribute
3) Add the other new attribute

As you are not using transactions, take into account that at any point, the migration can be interrupted and leave the database in an inconsistent state. We'll probably be adding "recovery" migration, which will be very handy in non-transaction environments.

With this approach you ensure  that the current attribute won't ever be deleted until the "new renamed one" is added. If changeSet1 failed abruptly, you still could have your app operative running  with the old state as nothing never happened. If it happens on changeSet2, you already have the "new renamed" attribute, so you can ignore the old one.

About the third changeSet, and referring to my first recommendation, if it's a totally independent change, not related to the previous two, I would run it in a separated changeLog. It gets more clear about the migrations history and so on.

**Comment by jfenuk** [comment]
@dieppa yeh, feel free to add it to the FAQ page, I think it is quite sensitive to know how to use the tool correctly.
