### ISSUE TITLE
Question about Undo Functionality

### ISSUE THREAD

**Issue by rebeccan** [cloudyrock/mongock#251]
Hi there,

I am trying to integrate Mongock as a migration tool and I am asking myself a few **questions**:

- will the undo feature be available soon or will it take some time until it is implemented and released?
- how intelligent will the Mongock Undo be? Will it be suitable to automatically solve alternate feature deployment of non backward compatible migrations, e.g. renaming a field of a collection?

The **problems I am trying to solve** are:

- after feature deployment on a dev environment with a ChangeLog0003, the develop branch is deployed where ChangeLog0003 is not yet existent, but the latest script is ChangeLog0002. It would be great to automatically detect that ChangeLog0003 is missing and undo all changes.
- after feature deployment on a dev environment with a ChangeLog0003, another branch is deployed where another developer has created another ChangeLog0003. It would be great to detect that the migration script has changed (checksum?), undo the old one and migrate the new one.

Do you have any **advice** for me? Is such an intelligent undo functionality planned and possible in Mongock? Can I make things faster with contributing? Or should I better look out for other solutions such as mongodump (will not be great either as added data will be lost after every recovery)? Do you have any other ideas?

Bests and thanks in advance,
Rebecca

**Comment by dieppa** [comment]
Hello @rebeccan ,

I don't fully understand the first problem you try to solve. You are saying that you are gong to deploy on a dev env where ChangeLog003 hasn't been deployed yet. But then, after detecting ChangeLog003 is missing, you'd like to undo all changes. What changes if ChangeLog003 hasn't been executed? 

For the problem 2, assuming undo is available, why don't provide and ChangeLog003_undo to fix what that "another developer" did and provide and ChangeLog004. It hasn't been implemented yet, but the idea is not removing the ChangeLog003 from the mongock's history(changeLog collection), but provide a mechanism to help to undo the effects or, if possible, not ever run it. It would be as marking a changeLog as failed, so if it has been run in an environment, it is fixed by undo, otherwise it's not run. That's the clearest way I can explain myself :D

Regarding your two first questions:
1) Both, it will take some time,  but it will soon. I am thinking about end of next week for a beta version and 2 weeks for a RC.
2) Well, by my previous explanation you can get an idea of  how intelligent/dummy it will be.

**Comment by rebeccan** [comment]
Hi dieppa,

thank you for your super fast response and it is great to hear that development of undo is planned so soon :-)

I think that you misunderstood the problems I try to find a solution for, so I try to explain it with more details and maybe you can tell me if the solutions in my head sound realistic.

**Problem 1:** We are developing features independently of each other and test their separate branches before they are merged to develop branch. In my example ChangeLog003 belongs to one feature branch (A) and is an non-backward compatible migration (e.g. rename of a field of a collection). A is deployed and tested on a dev environment. After that, another feature (B) is deployed and tested that is based on develop (no migrations added), but has no clue of the other feature with ChangeLog003. The Code from B with a Java object with the old fieldname is unfortunately not compatible anymore with the database schema, because A executed ChangeLog003 (renamed the field) and did not undo its migration in the database once undeployed. 

**Possible solution to problem 1 which is currently in my head:** If there was some kind of mechanism to detect that ChangeLog003 is missing now in currently deployed B (we could know that because ChangeLog003.java is missing in the code, but was executed according to the mongockChangeLog collection) and if we knew what the reverse migration operations of ChangeLog003 are, then we could undo it.

**Problem 2:** Also here we have independent feature branches A and B. The developer of B cannot provide a ChangeLog003_undo and ChangeLog004, because as long as A is not merged to develop branch yet, he has no clue that another developer wrote a ChangeLog003 migration as well. Both ChangeLog003 may do totally unrelated things in the database. 
I want to be able to test and deploy A and B on a dev environment in alternate turns without breaking compatibility of the application with the database.

**Possible solution to problem 2 which is currently in my head:** Same as above, but also detect that the latest script(s) has changed. Undo and migrate again in that case.

Keeping the mongock history collection untouched and applying migration after migration is only practical for our environments on which develop / master branch is deployed, because features are added sequentially and you have migrations that are applied one after each other. But even on such stable environment it would be awesome if a release rollback could be detected automatically by mongock so that undo does not have to be done manually.

What do you think of my suggestions?

Bests,
Rebecca

**Comment by dieppa** [comment]
Hello,

If I am not wrong both are kind of the same problem really but looked from different perspectives. 

Mongock cannot provide the solution you suggest as it doesn't feel right in a general case to assume a changeLog needs to be undone just because it's present in the changeLog collection but no in the code. Do you know what I mean? Anyway that approach would still have the issue of providing the actual "undo operation", Mongock cannot offer that as it's very difficult to handle that situation and with the current framework just not possible.

What I think it's the best approach, although it's the long path, is to have a clean dev environment where deploying feature branches. That means the database is totally clean when you do a new deployment and you populate it as part of the new deployment(obviously that process would only take place in no production environments).

Also there is something I don't understand, even for branch A, you (should) want to apply changeLog003 every time is deployed, unless you have a clean environment every time, it will be executed only the first time.


Anyway there are plenty of solutions, from better to worse, and from more durable to temporal fix/hacks. Temporal deployment script, feature toggling... But that totally depends on your situation and resources, which I am not familiar with.

Sorry for not being more helpful. Anyway, if you come up with a general solution that would be nice for Mongock to provide, please don't hesitate to let me know.

**Comment by rebeccan** [comment]
Hi @dieppa,

thank you for the clarification!

I don't think that it feels wrong if a migration tool (when the developer configures it that way) undoes things which are present in the changeLog collection, but not in the code. I was working with Java Flyway a few years ago, which ran checksums over the migration scripts in the code and compared it with the checksums logged of applied migrations in the database. It threw an error, if it detected mismatches. Honestly, an error also would not help in my case (and I can remember that there always was trouble with testing features, as well), but the approach "compare DB with code" generally exists in some migration tools. But of course it is up to Mongock developers how they want their migration tool to work :-)

I would also love to always start with a clean seeded database, but in our environments some people have much data which they need for testing and I prefer not to seed everything or let people recreate all their data all the time.
So the idea I came up with: undo all migrations on application shutdown and migrate all on every application start. I will wait for the undo functionality and hope that I can somehow trigger it from some application shutdown routine. Will migrations know that they were undone? Will they run again in that case?
What do you think?

Bests,
Rebecca

**Comment by dieppa** [comment]
First at all, about "it is up to Mongock developers how they want their migration tool to work", while we of course make the final call, it's for Mongock's users, so we really want to provide what you need. So we can really appreciate this kind of "issues" as make Mongock better. Thanks ;)

About that checksum, I know if it's something that has been used in other tools and it probably makes sense to them, but I personally don't like it. In my personal experience gives more headache than benefits. However, if we really need to consider it, we are totally open to. Anyway in this specific case I don't think it would solve your issue anyway.

Regarding what you suggested about undoing a change if it's in the changeLog collection but not in the code, while I don't like, I guess that could be an advance feature that you can switch on with properties. Until that point we are ok, right? But still you would need an undo process as Mongock cannot deduct what needs to be done. What are your thoughts about this?... I can think some dirty ways, but they are complex and hacky
