### ISSUE TITLE
Why does ChangeSet ID needs to be unique across all changelogs?

### ISSUE THREAD

**Issue by mh-mbhojane** [cloudyrock/mongock#252]
Hi,

So during initial adaptation of the tool, we found that the ChangetSet ID has to be unique across all change logs. When we had something like this:

```
@ChangeLog(order=001)
public class ChangeLog1 {
@ChangeSet(order=001, id=changeset1) 
public void changeset1(MongoDatabase db) {
//...
}
}
```

```
@ChangeLog(order=002)
public class ChangeLog2 {
@ChangeSet(order=001, id=changeset1)
public void changeset1(MongoDatabase db) {
//...
}
}
```

The `changeset1` in change log `ChangeLog2` was being skipped and not executed. Why does the tool not consider the class name when determining which migrations have executed? The class name is stored in the changelog table.

**Comment by dieppa** [comment]
Hello @mh-mbhojane ,

first to clarify that the changeSet's id doesn't need to be unique across all changeSets, the pair changeId, author is.

Regarding your question about not using className as the unique identifier, here there are a couple of reasons, but there are probably more:

1. Backward compatibility and make the framework more friendly for users. Keep in mind the first users came from a deprecated tool called MongoBee and it worked in that way. But not only that, similar tools such as Liquibase, flyway, etc. use that approach.
2. Best practice. It's always recommendable to use an explicit id for your changes, instead of using class name or other specific code origin, for less couple change logs, among other reasons.
3. There are more about best practices and that kind of stuff that are not really technical impediment, however one that is really a technical reason is...what happen if you decide to refactor your code? Simply you can't as your changeSet are tightly coupled with your code. 

I hope it makes sense to you :)

**Comment by dieppa** [comment]
...said that, it would be ideal if Mongock identify id duplication and throw an exception before even starting the migration...I am creating a issue for that ;)
