### ISSUE TITLE
Can you please provide the artifact dependencies for Gradel

### ISSUE THREAD

**Issue by nidhiGreyamp** [cloudyrock/mongock#280]

**Comment by dieppa** [comment]
Hello @nidhiGreyamp ,

what do you mean with dependencies for Gradle(I guess  " gradel" is a mistake)? You should be able to import the dependencies to a Gradle project

**Comment by nidhiGreyamp** [comment]
Apologies, it was typo. I meant Gradle. 
These are dependencies I have imported, 

    compile 'com.github.cloudyrock.mongock:mongock-core:4+'
    compile group: 'com.github.cloudyrock.mongock', name: 'mongock-bom', version: '4.0.3.alpha', ext: 'pom'
    compile group: 'com.github.cloudyrock.mongock', name: 'drivers', version: '4.1.16', ext: 'pom'
    compile group: 'com.github.cloudyrock.mongock', name: 'mongock-spring-v5', version: '4.1.19'
    compile group: 'com.github.cloudyrock.mongock', name: 'mongodb-springdata-v2-driver', version: '4.2.3.BETA'

Getting this error: "nested exception is java.lang.IllegalStateException: Failed to introspect annotated methods on class com.github.cloudyrock.spring.v5.MongockContext"

**Comment by dieppa** [comment]
Hello, 

I going to list the things I see wrong. You can try theses fixes and if you still find issues, let me know.

1. You don't need to import **name: 'drivers', version: '4.1.16', ext: 'pom'**
2. You are using a different version for each artifact. It should be the same. Actually, the idea of importing the **bom** is to configure the version of the actual artifacts. You can see an example [here](https://blog.mrhaki.com/2019/04/gradle-goodness-use-bill-of-materials.html)
3. Please, take a look to our [documentation](https://www.mongock.io/), which is shown in our readme


I hope you find this useful

**Comment by nidhiGreyamp** [comment]
Added these and it worked, thanks! 

    implementation 'com.github.cloudyrock.mongock:mongock-bom:4.2.3.BETA'
    implementation 'com.github.cloudyrock.mongock:mongock-spring-v5:4.2.3.BETA'
    implementation 'com.github.cloudyrock.mongock:mongock-standalone:4.2.3.BETA'
    implementation 'com.github.cloudyrock.mongock:mongodb-sync-v4-driver:4.2.3.BETA'
    implementation 'com.github.cloudyrock.mongock:mongodb-springdata-v2-driver:4.2.3.BETA'

**Comment by dieppa** [comment]
Hello,

I am glad it works, but still it's not right. Although I think it' well explained in our [documentation](https://www.mongock.io/quick-start), I will try to be more specific and explicit, so you can configure the project rightly:

1. You only need to import **one runner** and **one driver**. Only one of each.
2. For runner you need to pick **either** mongock-spring-v5 **or(exclusively)** mongock-standalone
3. For driver you need to pick **either** mongodb-sync-v4-driver **or(exclusively)**  mongodb-springdata-v2-driver
4. If you import the **B**ill **O**f **M**aterial(BOM) as the link I provided shows, you don't need to specify the version for the artifacts. Otherwise there is no point in importing the bom dependency.

- Despite of the points **2** and **3**, we recommend to use on of the following combinations of runner-driver:
   - mongock-spring-v5 + mongodb-springdata-v2-driver(or v3 if you are using Spring data 3 in your project)
   - mongock-standalone + mongodb-sync-v4-driver(or mongodb-v3-driver)

- Please note that Mongock driver `mongodb-springdata-v3-driver` is intended to be used if you are using Spring Data 3 in your project, as well as `mongodb-springdata-v2-driver` should be used if you are using Spring Data 2 instead.

The suggested way if you are using Spring data 2, as it seems, is:
```groovy
dependencies {
    // import a BOM
    implementation platform('com.github.cloudyrock.mongock:mongock-bom:4.2.3.BETA')

    // impot dependencies without versions
    implementation 'com.github.cloudyrock.mongock:mongock-spring-v5'
    implementation 'com.github.cloudyrock.mongock:mongodb-springdata-v2-driver'

   // you also need to import the MongoDB and Spring data dependencies
    implementation 'org.mongodb:mongo-java-driver:3.11.0' 
    implementation 'org.springframework.data:spring-data-mongodb:2.2.4.RELEASE'
}
```

I hope you find this useful ;)

**Comment by nidhiGreyamp** [comment]
Thank you so much! 🙏🏼
