### ISSUE TITLE
Multiple database mongocktemplate issue

### ISSUE THREAD

**Issue by VikasCarscan** [cloudyrock/mongock#290]
I have multiple mongotemplate configurations in my application.

Steps to reproduce :
run mvn clean install

Im using spring boot 2x with the annotation based approach

I have marked my bean as primary in spring code but the mongocktemplate always refers to the other mongotemplate

**Comment by dieppa** [comment]
Hello,

have you tried to create another bean, which takes the MongoTemplate, to see if takes the primary or the one Mongock is taken? Just to see.

If it takes the primary, there is a bug in Mongock, otherwise, you are doing something wrong.

Let me know, thanks

**Comment by VikasCarscan** [comment]
Hello,
I have marked MongoTemplate as primary. When i run it with SpringBoot main application it works as expected. Only on maven clean install the MongockTemplate takes the other bean.

**Comment by dieppa** [comment]
Hello, I don't really understand what you mean.  If only happens with Mongock, if only happens when doing `mvn clean install` only for Mongock or all the beans, etc.

What I wanted to say it's you to prove that only happens with Mongock and no other beans. Because Mongock Configuration is just a normal Spring boot configuration which requires a MongoTemplate bean. I would be surprise if that is related to Mongock itself. I would bet is something you are doing related to Spring and affects to any other bean that get the MongoTemplate injected.

Do you get my point?

**Comment by VikasCarscan** [comment]
So here is the thing:
When i run the application using the java -jar command the spring context wires the bean based on the @Primary annotation and MongockTemplate gets the right bean. When i run the mvn clean install/package in the migration @ChangeLog class the mongocktemplate picks the other injected mongotemplate.
Is there a way to exclude it out of the build phase of maven so that mongock only runs when when the application starts up ?

**Comment by VikasCarscan** [comment]
Also are there any sample example code which i can refer to for standalone setup with custom configuration for spring boot 2x

**Comment by dieppa** [comment]
Ok, as I was thinking that issue is not related to Mongock,but to your spring setup.

A workaround, as you mention, is to prevent mongock from running at that stage. Notice that there is the `enable` flag, which being `false` will prevent Mongock from running.

You could do our setup that based on a jvm argument you switch off that flag. Or using a maven profile. That's your call, but  I guess the "fix" is around that `enabled` flag.

Regarding the examples for standalone application. We'll provide that in together with several new features in the coming  version 5. Anyway, unless you have a good reason for it, I don't recommend it, if you are using Spring boot.

Regards

**Comment by dieppa** [comment]
Please can you update this issue? Otherwise we'll assume is fixed and it will be closed.

thanks

**Comment by VikasCarscan** [comment]
Hi Sir,
Is it possible that we setup a teams/skype call. ?  The tool is awesome but really  would need your help and expertise  with my current config since we are going to live with our module on production. I have tried fixing it on my end but as explained in the previous issue i am facing difficulties for the same.

**Comment by dieppa** [comment]
Please send an email to dev@cloudyrock.io

**Comment by dieppa** [comment]
I haven't received any email, but you may want to take a look to the [example project for multiple mongoTemplates](https://github.com/cloudyrock/mongock-examples/tree/master/mongoDB/version4_x/spring5-springdata3-multiple-templates)

**Comment by VikasCarscan** [comment]
> I haven't received any email, but you may want to take a look to the [example project for multiple mongoTemplates](https://github.com/cloudyrock/mongock-examples/tree/master/mongoDB/version4_x/spring5-springdata3-multiple-templates)

I have mailed you from my company id. The example here refers to same database for multiple templates.
It would be wonderful if you could add multiple database example too
