### ISSUE TITLE
4.3.0 is using SNAPSHOT dependencies version

### ISSUE THREAD

**Issue by DanielFran** [cloudyrock/mongock#291]
**Describe the bug** 

Cannot use current version 4.3.0 because it uses SNAPSHOT dependencies.
![imagem](https://user-images.githubusercontent.com/3706415/106723836-70e42d80-65ff-11eb-9a21-574200d26d3f.png)

See https://github.com/cloudyrock/mongock/pull/289/files#diff-6d3b8e38bec2aaa78da8cd1ce19a25753752de347f6ccb0223e0e2fe5cc28c8bR17

**To Reproduce**

See  https://github.com/jhipster/jhipster-bom/pull/160/checks?check_run_id=1819652928

**Comment by dieppa** [comment]
@DanielFran We found the issue. I will notify you soon with the fix

**Comment by dieppa** [comment]
Hello @DanielFran. Apparently we made a mistake upgrading the versions in our integration tests and then, due to extra load on nexus servers, we spent more time than expected releasing the new version.

But finally we managed to release the version 4.3.2. It should work.

Please let me know if you need anything else.

Thanks
