### ISSUE TITLE
Usage with SpringBoot - ApplicationRunner

### ISSUE THREAD

**Issue by axelhodler** [cloudyrock/mongock#61]
As of now the library uses `ApplicationRunner`, thus the migrations will run after the app has started.

I would like to have the application start fail if my migrations fail.

I did not find a way to configure this.

Would it be a welcome addition to the codebase to add this feature if it's not yet configurable?

**Comment by dieppa** [comment]
Hi @axelhodler ,
that's true if you use SpringBootMongockBuilder. The reason why is because you want to inject your dependencies. So you need to wait at that phase for the migration to run.

However, I believe SpringMogockBuilder(Notice it's not SpringBoot) fits your requirements. 

Please, let me know if I am right or I haven't understood your issue.

**Comment by axelhodler** [comment]
@dieppa exactly what i wanted. Thanks a bunch and keep up the good work 👍
