### ISSUE TITLE
Spring boot executable jar application does not see classes with ChagneLogs

### ISSUE THREAD

**Issue by glowjan** [cloudyrock/mongock#88]
When our application is packaged as executable spring boot jar ChangeLog classes inside this jar are not seen. It was working in version 3.0.0-BETA. It looks like changes in: https://github.com/cloudyrock/mongock/pull/76/commits/20fe854375a1141e069e98d8ecec457f26f0a1a6 in method fetchChangeLogs causes the problem

With prior versions this was working well and also when the application is not packaged as spring-boot than ChangeLogs are also seen with no problems.

**Comment by dieppa** [comment]
Hello guys. 
When we are back from vacations we'll go into details and see what exactly happened in order to try to bring this change back without issues.

Meanwhile new beta has been released with that change rolled back. Please, have a shoot and let us know if it fixes it.

`<dependency>
  <groupId>com.github.cloudyrock.mongock</groupId>
  <artifactId>mongock-core</artifactId>
  <version>3.0.3.BETA</version>
</dependency>`

Thanks

**Comment by glowjan** [comment]
Yes, this version is working for me. Thanks for this quick fix.

**Comment by savvadem** [comment]
yep, docker fixed too

**Comment by dieppa** [comment]
great. Thanks guys
